### ISSUE TITLE
getEnv deprecated?

### ISSUE THREAD

**Issue by ianpdavies** [RRemelgado/rsMove#3]
I stumbled across this package and it's `getEnv()` function to download JRC Global Surface Water data here (https://www.rdocumentation.org/packages/rsMove/versions/0.2.1/topics/getEnv). Aside from that webpage, it doesn't seem to be, or have ever been, in this package. Is this function lying around somewhere?

**Comment by RRemel** [comment]
The package is currently on version 0.2.3 in which it was deprecated. Decided to do so because my developed a dedicated package for the download of spatial data. See [here](https://github.com/16EAGLE/getSpatialData).
